/**
 * Built-in model configuration.
 *
 * Users extend or override this with `<data dir>/models/models.json` — adding
 * another compatible model is a configuration change, not a code change.
 * Model availability is verified at runtime against the provider's own model
 * list; nothing here is assumed to exist.
 */
import type { ModelDefinition, ProviderConfig } from "./types";

export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  {
    id: "gemini",
    apiType: "gemini",
    displayName: "Google Gemini",
    secretName: "provider:gemini",
    enabled: true,
    locality: "cloud",
  },
  {
    // Template for Ollama / LM Studio / llama.cpp / vLLM. Enable in models.json.
    id: "local",
    apiType: "openai-compatible",
    displayName: "Local (OpenAI-compatible)",
    baseUrl: "http://127.0.0.1:11434/v1",
    enabled: false,
    locality: "local",
  },
  {
    id: "openai",
    apiType: "openai-compatible",
    displayName: "OpenAI-compatible cloud",
    baseUrl: "https://api.openai.com/v1",
    secretName: "provider:openai",
    enabled: false,
    locality: "cloud",
  },
  {
    id: "anthropic",
    apiType: "anthropic-compatible",
    displayName: "Anthropic-compatible",
    baseUrl: "https://api.anthropic.com",
    secretName: "provider:anthropic",
    enabled: false,
    locality: "cloud",
  },
];

const geminiText = {
  vision: true,
  tools: true,
  structuredOutput: true,
  reasoning: true,
  streaming: true,
  liveAudio: false,
  embedding: false,
};

export const DEFAULT_MODELS: ModelDefinition[] = [
  {
    id: "gemini-3.5-flash",
    displayName: "Gemini 3.5 Flash",
    provider: "gemini",
    modelName: "gemini-3.5-flash",
    apiType: "gemini",
    capabilities: geminiText,
    contextLength: 1_048_576,
    tier: "balanced",
    locality: "cloud",
    cost: { note: "See Google AI pricing" },
    accent: "#22d3ee",
    icon: "sparkles",
    recommendedTasks: ["conversation", "planning", "vision", "grounding", "summarization"],
    description: "Default brain. Fast multimodal reasoning for desktop control and conversation.",
    enabled: true,
    options: { thinkingLevel: "low" },
  },
  {
    id: "gemini-3.8-flash",
    displayName: "Gemini 3.8 Flash",
    provider: "gemini",
    modelName: "gemini-3.8-flash",
    apiType: "gemini",
    capabilities: geminiText,
    contextLength: 1_048_576,
    tier: "balanced",
    locality: "cloud",
    cost: { note: "See Google AI pricing" },
    accent: "#818cf8",
    icon: "zap",
    recommendedTasks: ["planning", "vision", "grounding", "coding"],
    description: "Newer Flash generation. Stronger visual grounding and multi-step planning.",
    enabled: true,
    options: { thinkingLevel: "medium" },
  },
  {
    id: "gemini-3.5-flash-lite",
    displayName: "Gemini 3.5 Flash-Lite",
    provider: "gemini",
    modelName: "gemini-3.5-flash-lite",
    apiType: "gemini",
    capabilities: { ...geminiText, reasoning: false },
    contextLength: 1_048_576,
    tier: "fast",
    locality: "cloud",
    cost: { note: "Lowest cost Gemini text tier" },
    accent: "#34d399",
    icon: "feather",
    recommendedTasks: ["conversation", "classification", "summarization"],
    description: "Quickest replies. Used by AUTO for light chat, classification and summaries.",
    enabled: true,
  },
  {
    id: "gemini-3.1-pro-preview",
    displayName: "Gemini 3.1 Pro (preview)",
    provider: "gemini",
    modelName: "gemini-3.1-pro-preview",
    apiType: "gemini",
    capabilities: geminiText,
    contextLength: 1_048_576,
    tier: "deep",
    locality: "cloud",
    cost: { note: "Higher cost, slower" },
    accent: "#f472b6",
    icon: "brain",
    recommendedTasks: ["planning", "coding"],
    description: "Deep reasoning for long, ambiguous or coding-heavy tasks.",
    enabled: true,
    options: { thinkingLevel: "high" },
  },
  {
    id: "gemini-3.1-flash-live-preview",
    displayName: "Gemini 3.1 Flash Live",
    provider: "gemini",
    modelName: "gemini-3.1-flash-live-preview",
    apiType: "gemini",
    capabilities: { ...geminiText, liveAudio: true, structuredOutput: false },
    contextLength: 131_072,
    tier: "fast",
    locality: "cloud",
    cost: { note: "Realtime audio pricing" },
    accent: "#a78bfa",
    icon: "mic",
    recommendedTasks: ["live_voice"],
    description: "Realtime voice conversation (speech in, speech out, barge-in).",
    enabled: true,
    options: { voiceName: "Aoede" },
  },
  {
    id: "gemini-3.8-live",
    displayName: "Gemini 3.8 Live",
    provider: "gemini",
    modelName: "gemini-3.8-live",
    apiType: "gemini",
    capabilities: { ...geminiText, liveAudio: true, structuredOutput: false },
    contextLength: 131_072,
    tier: "balanced",
    locality: "cloud",
    cost: { note: "Realtime audio pricing" },
    accent: "#c084fc",
    icon: "mic",
    recommendedTasks: ["live_voice"],
    description: "Newer realtime voice model.",
    enabled: true,
    options: { voiceName: "Aoede" },
  },
  {
    id: "gemini-embedding-001",
    displayName: "Gemini Embedding",
    provider: "gemini",
    modelName: "gemini-embedding-001",
    apiType: "gemini",
    capabilities: { vision: false, tools: false, structuredOutput: false, reasoning: false, streaming: false, liveAudio: false, embedding: true },
    contextLength: 2_048,
    tier: "fast",
    locality: "cloud",
    cost: {},
    recommendedTasks: ["embedding"],
    description: "Text embeddings for memory retrieval.",
    enabled: true,
  },
  {
    id: "local-vision",
    displayName: "Local vision model",
    provider: "local",
    modelName: "qwen2.5vl:7b",
    apiType: "openai-compatible",
    capabilities: { vision: true, tools: true, structuredOutput: true, reasoning: false, streaming: true, liveAudio: false, embedding: false },
    contextLength: 32_768,
    tier: "balanced",
    locality: "local",
    cost: { note: "Runs on this PC" },
    accent: "#fbbf24",
    icon: "cpu",
    recommendedTasks: ["conversation", "vision", "planning"],
    description: "Template for an offline model served by Ollama/LM Studio. Disabled until configured.",
    enabled: false,
  },
];
